name: deploy to lambda

on:
  push:
    branches:
      - main


jobs:

  deploy:
    name: deploy lambda from source
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:

      - name: checkout source code
        uses: actions/checkout@v1
      - name: Use node.js ${{matrix.node-version}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node-version}}
      - uses: actions/setup-python@v4 
        with:
          python-version: 'pypy3.9'
      - name: configure serverless
        uses: serverless/github-action@master
        with: 
          args: config credentials --provider aws --key ${{secrets.AWS_ACCESS_KEY_ID}} --secret ${{secrets.AWS_SECRET_ACCESS_KEY}} -- profile mainprofile --overwrite
     
      - name: Serverless plugin install
        uses: serverless/github-action@master
        with:
          args:  plugin install -n serverless-python-requirements


      - name: serverless deploy
        uses: serverless/github-action@master
        with:
          args: deploy 
          
          args: deploy
      


          
      - name: serverless doctor 
        uses: serverless/github-action@master
        with:
          args: doctor
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          AWS_REGION: ${{secrets.AWS_REGION}}
